apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kubetool-test
  name: kubetool-test
  namespace: default
spec:
  replicas: 2
  selector:
    name: kubetool-test
  template:
    metadata:
      labels:
        name: kubetool-test
    spec:
      containers:
      - image: nginx
        name: kubetool-test

